# Generated by scripts/generate_recovery_contract.py from
# contracts/recovery-policy.v1.json -- do not edit by hand.
from __future__ import annotations

from typing import Final

CONTRACT_NAME: Final[str] = 'offerpilot.recovery-policy'
CONTRACT_VERSION: Final[int] = 1
DOMAIN: Final[str] = 'mock_interview'
DISPOSITIONS: Final[tuple[str, ...]] = ('retry_same_key', 'restart_new_attempt', 'reload_source', 'edit_input', 'terminal_no_retry')
ATTEMPT_RETENTIONS: Final[tuple[str, ...]] = ('retained_reconcile', 'retained_terminal', 'retained', 'absent')
UNKNOWN_CODE_DISPOSITION: Final[str] = 'terminal_no_retry'
UNKNOWN_CODE_PROVIDER_RETRY_ALLOWED: Final[bool] = False
NETWORK_TRANSPORT_DISPOSITION: Final[str] = 'retry_same_key'

class RecoveryPolicyEntry:
    """One error_code's frozen recovery contract."""

    __slots__ = (
        'error_code', 'http_status', 'disposition', 'attempt_retention',
        'input_frozen', 'preserve_idempotency_key', 'provider_retry_allowed',
        'user_action',
    )

    def __init__(self, error_code: str, http_status: int, disposition: str,
                 attempt_retention: str, input_frozen: bool,
                 preserve_idempotency_key: bool, provider_retry_allowed: bool,
                 user_action: str) -> None:
        self.error_code = error_code
        self.http_status = http_status
        self.disposition = disposition
        self.attempt_retention = attempt_retention
        self.input_frozen = input_frozen
        self.preserve_idempotency_key = preserve_idempotency_key
        self.provider_retry_allowed = provider_retry_allowed
        self.user_action = user_action

    def __repr__(self) -> str:
        return (
            f'RecoveryPolicyEntry({self.error_code}, disposition={self.disposition})'
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RecoveryPolicyEntry):
            return NotImplemented
        return self.error_code == other.error_code

    def __hash__(self) -> int:
        return hash(self.error_code)

RECOVERY_POLICIES: Final[dict[str, RecoveryPolicyEntry]] = {
    'application_jd_version_required': RecoveryPolicyEntry(
        error_code='application_jd_version_required',
        http_status=422,
        disposition='edit_input',
        attempt_retention='absent',
        user_action='edit_input',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'interview_practice_case_idempotency_conflict': RecoveryPolicyEntry(
        error_code='interview_practice_case_idempotency_conflict',
        http_status=409,
        disposition='edit_input',
        attempt_retention='absent',
        user_action='edit_input',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'interview_practice_case_invalid_payload': RecoveryPolicyEntry(
        error_code='interview_practice_case_invalid_payload',
        http_status=422,
        disposition='edit_input',
        attempt_retention='absent',
        user_action='edit_input',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'interview_practice_case_not_found': RecoveryPolicyEntry(
        error_code='interview_practice_case_not_found',
        http_status=404,
        disposition='reload_source',
        attempt_retention='absent',
        user_action='reload_source',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_answer_required': RecoveryPolicyEntry(
        error_code='mock_interview_answer_required',
        http_status=422,
        disposition='edit_input',
        attempt_retention='retained',
        user_action='edit_input',
        input_frozen=True,
        preserve_idempotency_key=True,
        provider_retry_allowed=False,
    ),
    'mock_interview_application_not_found': RecoveryPolicyEntry(
        error_code='mock_interview_application_not_found',
        http_status=404,
        disposition='reload_source',
        attempt_retention='absent',
        user_action='reload_source',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_attempt_confirmed': RecoveryPolicyEntry(
        error_code='mock_interview_attempt_confirmed',
        http_status=409,
        disposition='terminal_no_retry',
        attempt_retention='retained',
        user_action='none',
        input_frozen=True,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_attempt_not_found': RecoveryPolicyEntry(
        error_code='mock_interview_attempt_not_found',
        http_status=404,
        disposition='restart_new_attempt',
        attempt_retention='absent',
        user_action='restart_new_attempt',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_context_mismatch': RecoveryPolicyEntry(
        error_code='mock_interview_context_mismatch',
        http_status=404,
        disposition='restart_new_attempt',
        attempt_retention='absent',
        user_action='restart_new_attempt',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_feedback_result_unknown': RecoveryPolicyEntry(
        error_code='mock_interview_feedback_result_unknown',
        http_status=502,
        disposition='retry_same_key',
        attempt_retention='retained_reconcile',
        user_action='retry_same_key',
        input_frozen=True,
        preserve_idempotency_key=True,
        provider_retry_allowed=True,
    ),
    'mock_interview_idempotency_conflict': RecoveryPolicyEntry(
        error_code='mock_interview_idempotency_conflict',
        http_status=409,
        disposition='restart_new_attempt',
        attempt_retention='retained',
        user_action='restart_new_attempt',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_invalid_payload': RecoveryPolicyEntry(
        error_code='mock_interview_invalid_payload',
        http_status=422,
        disposition='edit_input',
        attempt_retention='absent',
        user_action='edit_input',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_provider_error': RecoveryPolicyEntry(
        error_code='mock_interview_provider_error',
        http_status=502,
        disposition='retry_same_key',
        attempt_retention='retained_reconcile',
        user_action='retry_same_key',
        input_frozen=True,
        preserve_idempotency_key=True,
        provider_retry_allowed=True,
    ),
    'mock_interview_question_result_unknown': RecoveryPolicyEntry(
        error_code='mock_interview_question_result_unknown',
        http_status=502,
        disposition='retry_same_key',
        attempt_retention='retained_reconcile',
        user_action='retry_same_key',
        input_frozen=True,
        preserve_idempotency_key=True,
        provider_retry_allowed=True,
    ),
    'mock_interview_review_draft_already_confirmed': RecoveryPolicyEntry(
        error_code='mock_interview_review_draft_already_confirmed',
        http_status=409,
        disposition='terminal_no_retry',
        attempt_retention='retained',
        user_action='none',
        input_frozen=True,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_source_conflict': RecoveryPolicyEntry(
        error_code='mock_interview_source_conflict',
        http_status=409,
        disposition='reload_source',
        attempt_retention='retained',
        user_action='reload_source',
        input_frozen=True,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_transcript_conflict': RecoveryPolicyEntry(
        error_code='mock_interview_transcript_conflict',
        http_status=409,
        disposition='retry_same_key',
        attempt_retention='retained_reconcile',
        user_action='retry_same_key',
        input_frozen=True,
        preserve_idempotency_key=True,
        provider_retry_allowed=True,
    ),
    'mock_interview_turn_idempotency_conflict': RecoveryPolicyEntry(
        error_code='mock_interview_turn_idempotency_conflict',
        http_status=409,
        disposition='restart_new_attempt',
        attempt_retention='retained',
        user_action='restart_new_attempt',
        input_frozen=False,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'mock_interview_unverifiable': RecoveryPolicyEntry(
        error_code='mock_interview_unverifiable',
        http_status=502,
        disposition='terminal_no_retry',
        attempt_retention='retained_terminal',
        user_action='restart_new_attempt',
        input_frozen=True,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
    'quick_practice_review_not_available': RecoveryPolicyEntry(
        error_code='quick_practice_review_not_available',
        http_status=422,
        disposition='terminal_no_retry',
        attempt_retention='retained',
        user_action='none',
        input_frozen=True,
        preserve_idempotency_key=False,
        provider_retry_allowed=False,
    ),
}

UNKNOWN_CODE_POLICY: Final[dict[str, object]] = {
    'disposition': 'terminal_no_retry',
    'attempt_retention': 'retained',
    'input_frozen': True,
    'preserve_idempotency_key': False,
    'provider_retry_allowed': False,
    'user_action': 'restart_new_attempt',
}

NETWORK_TRANSPORT_POLICY: Final[dict[str, object]] = {
    'disposition': 'retry_same_key',
    'attempt_retention': 'retained_reconcile',
    'input_frozen': True,
    'preserve_idempotency_key': True,
    'provider_retry_allowed': False,
    'user_action': 'retry_same_key',
}
