// Generated by scripts/generate_recovery_contract.py from
// contracts/recovery-policy.v1.json -- do not edit by hand.

export type RecoveryDisposition =
  | 'retry_same_key'
  | 'restart_new_attempt'
  | 'reload_source'
  | 'edit_input'
  | 'terminal_no_retry'
;

export type RecoveryUserAction =
  | 'retry_same_key'
  | 'restart_new_attempt'
  | 'reload_source'
  | 'edit_input'
  | 'none'
;

export type RecoveryAttemptRetention =
  | 'retained_reconcile'
  | 'retained_terminal'
  | 'retained'
  | 'absent'
;

export interface RecoveryPolicyEntry {
  error_code: string;
  http_status: number;
  disposition: RecoveryDisposition;
  attempt_retention: RecoveryAttemptRetention;
  input_frozen: boolean;
  preserve_idempotency_key: boolean;
  provider_retry_allowed: boolean;
  user_action: RecoveryUserAction;
}

export interface FallbackRecoveryPolicy {
  policy_name: string;
  disposition: RecoveryDisposition;
  attempt_retention: RecoveryAttemptRetention;
  input_frozen: boolean;
  preserve_idempotency_key: boolean;
  provider_retry_allowed: boolean;
  user_action: RecoveryUserAction;
}

export const CONTRACT_VERSION = 1;
export const DOMAIN = 'mock_interview';

export const RECOVERY_POLICIES: Readonly<Record<string, RecoveryPolicyEntry>> = {
  application_jd_version_required: {
    error_code: 'application_jd_version_required',
    http_status: 422,
    disposition: 'edit_input',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'edit_input',
  },
  interview_practice_case_idempotency_conflict: {
    error_code: 'interview_practice_case_idempotency_conflict',
    http_status: 409,
    disposition: 'edit_input',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'edit_input',
  },
  interview_practice_case_invalid_payload: {
    error_code: 'interview_practice_case_invalid_payload',
    http_status: 422,
    disposition: 'edit_input',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'edit_input',
  },
  interview_practice_case_not_found: {
    error_code: 'interview_practice_case_not_found',
    http_status: 404,
    disposition: 'reload_source',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'reload_source',
  },
  mock_interview_answer_required: {
    error_code: 'mock_interview_answer_required',
    http_status: 422,
    disposition: 'edit_input',
    attempt_retention: 'retained',
    input_frozen: true,
    preserve_idempotency_key: true,
    provider_retry_allowed: false,
    user_action: 'edit_input',
  },
  mock_interview_application_not_found: {
    error_code: 'mock_interview_application_not_found',
    http_status: 404,
    disposition: 'reload_source',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'reload_source',
  },
  mock_interview_attempt_confirmed: {
    error_code: 'mock_interview_attempt_confirmed',
    http_status: 409,
    disposition: 'terminal_no_retry',
    attempt_retention: 'retained',
    input_frozen: true,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'none',
  },
  mock_interview_attempt_not_found: {
    error_code: 'mock_interview_attempt_not_found',
    http_status: 404,
    disposition: 'restart_new_attempt',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'restart_new_attempt',
  },
  mock_interview_context_mismatch: {
    error_code: 'mock_interview_context_mismatch',
    http_status: 404,
    disposition: 'restart_new_attempt',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'restart_new_attempt',
  },
  mock_interview_feedback_result_unknown: {
    error_code: 'mock_interview_feedback_result_unknown',
    http_status: 502,
    disposition: 'retry_same_key',
    attempt_retention: 'retained_reconcile',
    input_frozen: true,
    preserve_idempotency_key: true,
    provider_retry_allowed: true,
    user_action: 'retry_same_key',
  },
  mock_interview_idempotency_conflict: {
    error_code: 'mock_interview_idempotency_conflict',
    http_status: 409,
    disposition: 'restart_new_attempt',
    attempt_retention: 'retained',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'restart_new_attempt',
  },
  mock_interview_invalid_payload: {
    error_code: 'mock_interview_invalid_payload',
    http_status: 422,
    disposition: 'edit_input',
    attempt_retention: 'absent',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'edit_input',
  },
  mock_interview_provider_error: {
    error_code: 'mock_interview_provider_error',
    http_status: 502,
    disposition: 'retry_same_key',
    attempt_retention: 'retained_reconcile',
    input_frozen: true,
    preserve_idempotency_key: true,
    provider_retry_allowed: true,
    user_action: 'retry_same_key',
  },
  mock_interview_question_result_unknown: {
    error_code: 'mock_interview_question_result_unknown',
    http_status: 502,
    disposition: 'retry_same_key',
    attempt_retention: 'retained_reconcile',
    input_frozen: true,
    preserve_idempotency_key: true,
    provider_retry_allowed: true,
    user_action: 'retry_same_key',
  },
  mock_interview_review_draft_already_confirmed: {
    error_code: 'mock_interview_review_draft_already_confirmed',
    http_status: 409,
    disposition: 'terminal_no_retry',
    attempt_retention: 'retained',
    input_frozen: true,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'none',
  },
  mock_interview_source_conflict: {
    error_code: 'mock_interview_source_conflict',
    http_status: 409,
    disposition: 'reload_source',
    attempt_retention: 'retained',
    input_frozen: true,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'reload_source',
  },
  mock_interview_transcript_conflict: {
    error_code: 'mock_interview_transcript_conflict',
    http_status: 409,
    disposition: 'retry_same_key',
    attempt_retention: 'retained_reconcile',
    input_frozen: true,
    preserve_idempotency_key: true,
    provider_retry_allowed: true,
    user_action: 'retry_same_key',
  },
  mock_interview_turn_idempotency_conflict: {
    error_code: 'mock_interview_turn_idempotency_conflict',
    http_status: 409,
    disposition: 'restart_new_attempt',
    attempt_retention: 'retained',
    input_frozen: false,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'restart_new_attempt',
  },
  mock_interview_unverifiable: {
    error_code: 'mock_interview_unverifiable',
    http_status: 502,
    disposition: 'terminal_no_retry',
    attempt_retention: 'retained_terminal',
    input_frozen: true,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'restart_new_attempt',
  },
  quick_practice_review_not_available: {
    error_code: 'quick_practice_review_not_available',
    http_status: 422,
    disposition: 'terminal_no_retry',
    attempt_retention: 'retained',
    input_frozen: true,
    preserve_idempotency_key: false,
    provider_retry_allowed: false,
    user_action: 'none',
  },
};

export const UNKNOWN_CODE_POLICY: FallbackRecoveryPolicy = {
  policy_name: 'fail_closed',
  disposition: 'terminal_no_retry',
  attempt_retention: 'retained',
  input_frozen: true,
  preserve_idempotency_key: false,
  provider_retry_allowed: false,
  user_action: 'restart_new_attempt',
};

export const NETWORK_TRANSPORT_POLICY: FallbackRecoveryPolicy = {
  policy_name: 'reconcile_same_key',
  disposition: 'retry_same_key',
  attempt_retention: 'retained_reconcile',
  input_frozen: true,
  preserve_idempotency_key: true,
  provider_retry_allowed: false,
  user_action: 'retry_same_key',
};
