"""Knowledge Imported Source Ingest 领域服务。

KI-03 范围：Markdown/Text 上传 + 粘贴正文 + 结构感知 Extraction + Evidence + FTS。
KI-04 范围：Source Bundle（Markdown 主文件 + PNG/JPEG/WebP 附件）+ Asset Evidence。
KI-07 范围：持久队列 / lease / 取消 / 恢复契约（``KnowledgeJobRunner``、扩展的
``ExtractionWorker.execute``）。
KI-09 范围：Brief generation + validation + 单事务提交当前 Brief。
"""

from offerpilot.knowledge.assets import (
    AssetInput,
    AssetValidationError,
    VerifiedAsset,
)
from offerpilot.knowledge.brief import (
    BRIEF_LANGUAGE,
    BRIEF_MIN_CONTEXT_WINDOW,
    BRIEF_PROMPT_VERSION,
    BRIEF_REPAIR_INVALID,
    BRIEF_REPAIR_PATCH_VERSION,
    BRIEF_REPAIR_UNAUTHORIZED,
    BRIEF_SCHEMA_VERSION,
    VALIDATION_PROMPT_VERSION,
    BriefPayload,
    BriefSchemaError,
    BriefSectionGuide,
    BriefStatement,
    BriefValidationReport,
    RepairOperation,
    RepairPatch,
    SupportDecision,
    apply_repair_patch,
    build_generation_prompt,
    build_repair_prompt,
    build_schema_repair_prompt,
    build_section_coverage_plan,
    build_validation_prompt,
    collect_brief_statement_blocks,
    parse_brief_payload,
    parse_repair_patch,
    parse_support_decision,
    validate_brief_against_evidence,
)
from offerpilot.knowledge.encoding import (
    DecodedContent,
    EncodingError,
    decode_source_bytes,
)
from offerpilot.knowledge.evidence_policy import (
    EVIDENCE_POLICY_VERSION,
    RULE_LABELS,
)
from offerpilot.knowledge.extractor import (
    EXTRACTOR_VERSION,
    METADATA_EXTRACTION_VERSION,
    MarkdownExtraction,
    MarkdownExtractor,
    compute_bundle_source_hash,
    compute_source_hash,
)
from offerpilot.knowledge.repository import (
    AssetCreateInput,
    BriefAttemptCreateInput,
    BriefAttemptRecord,
    EvidenceRecord,
    EvidenceSearchHit,
    JobRecord,
    KnowledgeBriefAttemptError,
    KnowledgeRepository,
    SourceAssetRecord,
    SourceBriefRecord,
    SourceRecord,
    SourceSnapshotRecord,
)
from offerpilot.knowledge.service import IngestError, IngestRequest, KnowledgeIngestService
from offerpilot.knowledge.tokenizer import TOKENIZER_VERSION, count_tokens
from offerpilot.knowledge.worker import (
    BriefWorker,
    ExtractionWorker,
    JobExecutionResult,
    KnowledgeJobRunner,
)

__all__ = [
    "AssetCreateInput",
    "AssetInput",
    "AssetValidationError",
    "BRIEF_LANGUAGE",
    "BRIEF_MIN_CONTEXT_WINDOW",
    "BRIEF_PROMPT_VERSION",
    "BRIEF_REPAIR_INVALID",
    "BRIEF_REPAIR_PATCH_VERSION",
    "BRIEF_REPAIR_UNAUTHORIZED",
    "BRIEF_SCHEMA_VERSION",
    "BriefAttemptCreateInput",
    "BriefAttemptRecord",
    "BriefPayload",
    "BriefSchemaError",
    "BriefSectionGuide",
    "BriefStatement",
    "BriefValidationReport",
    "BriefWorker",
    "DecodedContent",
    "EXTRACTOR_VERSION",
    "EncodingError",
    "EVIDENCE_POLICY_VERSION",
    "EvidenceRecord",
    "EvidenceSearchHit",
    "ExtractionWorker",
    "IngestError",
    "IngestRequest",
    "JobExecutionResult",
    "JobRecord",
    "KnowledgeBriefAttemptError",
    "KnowledgeIngestService",
    "KnowledgeJobRunner",
    "KnowledgeRepository",
    "MarkdownExtraction",
    "MarkdownExtractor",
    "METADATA_EXTRACTION_VERSION",
    "RepairOperation",
    "RepairPatch",
    "SupportDecision",
    "SourceAssetRecord",
    "SourceBriefRecord",
    "SourceRecord",
    "SourceSnapshotRecord",
    "TOKENIZER_VERSION",
    "VALIDATION_PROMPT_VERSION",
    "VerifiedAsset",
    "apply_repair_patch",
    "build_generation_prompt",
    "build_repair_prompt",
    "build_schema_repair_prompt",
    "build_section_coverage_plan",
    "build_validation_prompt",
    "collect_brief_statement_blocks",
    "compute_bundle_source_hash",
    "compute_source_hash",
    "count_tokens",
    "decode_source_bytes",
    "parse_brief_payload",
    "parse_repair_patch",
    "parse_support_decision",
    "RULE_LABELS",
    "validate_brief_against_evidence",
]
